services:
  db:
    container_name: db
    networks:
      - tracker-network
    image: postgres:12-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${TRACKER_DB}
      POSTGRES_USER: ${USER_TRACKER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_TRACKER_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "${TRACKER_PORT_DB}:${TRACKER_PORT_DB}"

networks:
  tracker-network:
    driver: bridge
